const _bio_terrafund ={
 bryan:{ 
     name:'BRYAN SAMA–AMBE',
 title:'DIRECTOR OF ECONOMICS',
 img:"assest/img/Bryan_Samme.png",
 bio:`Bryan is a detail–oriented, quality–conscious and well–trained finance professional with multiple years of experience working as the Director of Economics for The Terra Fund. His experience working with various small, medium and large businesses and financial corporations in Africa coupled with his expertise in the field of financial advising and consulting makes him a vital part of our team. 
 His proficiency in English and French, largely due to the work he has done across Africa makes him the ideal investment professional because of his ability to bridge the communication gap and offer advice to a wider range of clientele. His international exposure has also provided him with valuable experience pertaining to the functioning of the financial sector in a number of countries including Cameroon, Ghana and Ethiopia. With this history, he is able to offer investment solutions on the functioning of various securities including mutual funds and exchange–traded funds.
 Throughout his career, he has worked with both individual – families and trusts, and corporate clients – mutual funds, hedge funds, public/private pension plans, banking institutions and governments. During this time, he has honed his technological, management skills and applied a variety of investment techniques and strategies of valuation and growth, to guide Terra on how to efficiently manage their investments. Furthermore, his educational background provides the strong technical and analytical finance skills necessary to excel in this field, including financial reporting, financial statement analysis, portfolio management and market trend analysis.
 Bryan is a holder of both a Bachelor of Science (Hons) degree in Banking and Finance from the Cameroon Christian University Bali – Cameroon and obtained a Postgraduate Degree in Financial Analysis from the University of Western Australia. With a notable financial academic background and a wealth of professional experience, he has quickly boosted his place as a vital part of our team and plays his own part in pushing towards the intrinsic and future growth of our company.`,
},
hamza:{
    name:'HAMZA ARIF',
    title:'DIRECTOR OF FINANCE',
    img:'assest/img/hamza.png',
    bio:`Hamza is a seasoned, dedicated and detail–attentive capital finance professional who holds the position of Director of Finance at The Terra Fund. His experience in financial affairs, methodical orientation and economics have played a major part in providing the capital reporting requirements of various small and large organizations both domestic and abroad. 
 Over the course of his career, he has showcased his knowledge and technical prowess at a number of notable corporations, including Awais & Company Management and Tax Consultants where he performed large–volume financial and accounting services. By performing various functions including asset, liability and capital account management, value–added tax (VAT) and risk assessment and analysis, he continues to prove himself as a valuable member of our company. His excellent mastery of bookkeeping software has empowered him to accurately perform a variety of support functions, including audit analysis, ensuring professional and accurate representation of fiscal transactions.
 His excellent communication and interpersonal skills provides the tools necessary for him to effectively intersect and collaborate with other team members at Terra, as well as socially engage with current and potential investors. As an expert in the field of financial and management reporting, he constantly delivers his vast array of practical and analytical skills to deliver safe and well–informed decisions in this ever increasing complex and multinational marketplace. 
 His career in accountancy began at Oxford Brookes University where he obtained a Bachelor of Science (Hons) degree in Applied Accounting before moving on to study for and obtaining the Association of Chartered Certified Accountants (ACCA) qualification. From the moment he joined the team, his financial expertise and his experience interacting with individual and corporate clients have assisted him to effortlessly navigate the financial landscape and play a major part in the accomplishment of meeting the objects and goals of Terra.`,
},
marie:{
    name:'MARIE–CHRISTINE BROTHETON, MBA / PHD',
    img:'assest/img/marieed.jpg',
    title:'DIRECTOR OF SOCIAL IMPACT RESEARCH',
    bio:`Marie–Christine is the Director of Social Impact Research at The Terra Fund, where she is an expert in the fields of science and business and merges her knowledge, expertise and talent to provide financial opportunities driving change. Fluent in English and French, she is bridging communication gaps between healthcare and business partners, engaging in socially responsible investments, and providing investors with the knowledge and insight to make informed choices by demonstrating strong collaboration and continues to assist in developing and institute programs worldwide.
Previously, she showcased her expertise through publications and presentations having successfully secured funding for pharmaceutical research and economic development programs. As a scientist at Laval University, she is actively involved in designing and implementing curriculums to drive breakthrough technologies advancing the medical and environmental fields. Furthermore, she has been able to diversify her contribution to sustainable development by providing consulting advice on investment and industry opportunities in multiple fields, including chemical, computer, education, manufacturing and among other sectors. 
Since partnering with Terra, her skills have quickly become a valuable resource to the team, by understanding the difficulties of acquiring grants and funding, she has helped nurture a new network of partners and opened doors to innovative opportunities in multiple countries. Her knowledge and expertise in the field of pharmaceuticals allows her to identify, quantify, and position potential investments to institutions and corporations reinforced by scientific facts, as she utilizes her financial and business prowess to secure relationships and resources for Terra and our partners. 
Marie–Christine attended the University of Laval and graduated with a Bachelor of Science in Microbiology and extended her education by attaining an MSc and PhD in the specialized field of cellular and molecular biology with a thesis on proteomic studies, she then went on to obtain an MBA in Corporate Social and Environment Responsibility. `,
}
}